version: '3.8'

services:
  sub_serv:
    build:
      context: ./sub
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - bargain_net

  bot_serv:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - bargain_net

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - bargain_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bargain_net

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  bargain_net:
    driver: bridge
